import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  appContainer: { flex: 1, backgroundColor: '#0f172a' },
  mainContainer: { flex: 1, backgroundColor: '#0f172a' },
  centeredContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  loadingText: { marginTop: 8, color: '#9ca3af' },
  loginContainer: { flex: 1, paddingHorizontal: 24, justifyContent: 'center' },
  appTitle: { fontSize: 32, fontWeight: '800', color: '#e5e7eb', textAlign: 'center', marginBottom: 8 },
  appSubtitle: { fontSize: 14, color: '#9ca3af', textAlign: 'center', marginBottom: 32 },
  landingSubtitle: { fontSize: 15, color: '#cbd5f5', textAlign: 'center', marginBottom: 12 },
  landingBody: { fontSize: 13, color: '#9ca3af', textAlign: 'center', marginBottom: 24, lineHeight: 18 },
  loginForm: {
    backgroundColor: '#020617',
    padding: 20,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#1f2937',
  },
  screenContainer: { flex: 1, paddingHorizontal: 16, paddingTop: 12, paddingBottom: 4 },
  screenTitle: { fontSize: 22, fontWeight: '700', color: '#e5e7eb', marginBottom: 10 },
  scrollContent: { paddingBottom: 80 },
  card: {
    backgroundColor: '#020617',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#1f2937',
  },
  cardTitle: { fontSize: 18, fontWeight: '700', color: '#e5e7eb' },
  cardSubtitle: { fontSize: 14, color: '#9ca3af', marginTop: 2 },
  cardMeta: { fontSize: 12, color: '#6b7280', marginTop: 2 },
  cardDifficulty: { fontSize: 12, color: '#9ca3af', marginTop: 6 },
  cardDifficultyValue: { fontWeight: '600', color: '#38bdf8' },
  cardDescription: { fontSize: 13, color: '#d1d5db', marginTop: 8, lineHeight: 18 },
  button: {
    marginTop: 10,
    paddingVertical: 8,
    borderRadius: 999,
    alignItems: 'center',
    backgroundColor: '#22c55e',
  },
  buttonText: { color: '#020617', fontWeight: '600', fontSize: 14 },
  buttonSecondary: { backgroundColor: '#020617', borderWidth: 1, borderColor: '#374151' },
  buttonSecondaryText: { color: '#e5e7eb', fontWeight: '600', fontSize: 14 },
  primaryButton: {
    marginTop: 16,
    backgroundColor: '#22c55e',
    paddingVertical: 10,
    borderRadius: 999,
    alignItems: 'center',
  },
  primaryButtonText: { color: '#020617', fontWeight: '700', fontSize: 16 },
  primaryButtonDisabled: { opacity: 0.7 },
  inputLabel: { fontSize: 13, color: '#9ca3af', marginTop: 12, marginBottom: 4 },
  input: {
    backgroundColor: '#020617',
    borderWidth: 1,
    borderColor: '#1f2937',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
    color: '#e5e7eb',
    fontSize: 14,
  },
  inlineError: { marginTop: 4, fontSize: 12, color: '#fca5a5' },
  multilineInput: { height: 80, textAlignVertical: 'top' },
  formContainer: { paddingBottom: 120 },
  profileCard: {
    backgroundColor: '#020617',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#1f2937',
  },
  profileLabel: { fontSize: 12, color: '#9ca3af', marginTop: 4 },
  profileValue: { fontSize: 16, fontWeight: '600', color: '#e5e7eb', marginBottom: 4 },
  profileEditButton: { marginTop: 12 },
  profileButtonsRow: { flexDirection: 'row', marginTop: 12 },
  profileButton: { flex: 1, marginHorizontal: 4 },
  emptyStateCard: {
    backgroundColor: '#020617',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#1f2937',
    padding: 16,
    marginTop: 8,
  },
  emptyText: { fontSize: 13, color: '#9ca3af' },
  tabBar: {
    flexDirection: 'row',
    backgroundColor: '#020617',
    paddingVertical: 8,
    paddingHorizontal: 8,
    borderTopWidth: 1,
    borderColor: '#1f2937',
  },
  tabItem: { flex: 1, paddingVertical: 8, borderRadius: 999, alignItems: 'center' },
  tabItemActive: { backgroundColor: '#111827' },
  tabLabel: { fontSize: 12, color: '#9ca3af', fontWeight: '500' },
  tabLabelActive: { color: '#22c55e', fontWeight: '700' },
  orText: { marginTop: 16, fontSize: 13, color: '#9ca3af', textAlign: 'center' },
  signupButtonsRow: { flexDirection: 'row', marginTop: 8 },
  signupButton: { flex: 1, marginHorizontal: 4 },
  groupMembersContainer: { marginTop: 24, alignItems: 'center' },
  groupTitle: { fontSize: 14, fontWeight: '700', color: '#e5e7eb', marginBottom: 4 },
  groupMemberText: { fontSize: 13, color: '#9ca3af' },
  logoutButton: { marginTop: 20, backgroundColor: '#ef4444' },
  logoutButtonText: { color: '#f9fafb', fontWeight: '700', fontSize: 14 },
  statusText: { marginTop: 10, color: '#fca5a5', fontSize: 12, lineHeight: 16 },
  demoInlineBox: { marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: '#1f2937' },
  demoTitle: { color: '#e5e7eb', fontWeight: '800', marginBottom: 6, fontSize: 14 },
  demoText: { color: '#9ca3af', fontSize: 12, marginTop: 2 },
  demoFillButton: { marginTop: 10 },
});
